name: Setup Go & Run Integration Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  setup-go:
    if: github.event.pull_request.head.repo.fork
    name: setup-go
    runs-on: ubuntu-latest
    env:
      SERV_ADDR: ${{ vars.SERV_ADDR }}
      PORT: ${{ vars.PORT }}
      POSTGRESQL_CONNECTION_STRING: ${{ vars.POSTGRESQL_CONNECTION_STRING }}
      DB_NAME: ${{ vars.DB_NAME }}
      DRIVER_NAME: ${{ vars.DRIVER_NAME }}
      USER_DATA_FILE_PATH: ${{ vars.USER_DATA_FILE_PATH }}
      MIGRATION_FILE_PATH: ${{ vars.MIGRATION_FILE_PATH }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.21.1
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          go get -v ./...

      - name: Integration Tests
        run: |
          go test -v ./...